name: TSR CI/CD PIPELINE
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: BUILD and PUSH
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tag: ${{ secrets.DOCKERHUB_USERNAME}}/flaskapp:dev-${{ github.run_number }}

      
